# config valid for current version and patch releases of Capistrano
lock '~> 3.10.0'

set :application, 'canvas'
set :repo_url, 'git@github.com:front/canvas-lms.git'
set :deploy_user, 'canvas'

# Default branch is :master
# ask :branch, `git rev-parse --abbrev-ref HEAD`.chomp

# Default value for :format is :airbrussh.
# set :format, :airbrussh

# You can configure the Airbrussh format using :format_options.
# These are the defaults.
# set :format_options, command_output: true, log_file: 'log/capistrano.log', color: :auto, truncate: :auto

# Default value for :pty is false
# set :pty, true

# Default value for :linked_files is []
append :linked_files, 'config/amazon_s3.yml',
											'config/dynamic_settings.yml',
											'config/database.yml',
											'config/delayed_jobs.yml',
											'config/domain.yml',
											'config/external_migration.yml',
											'config/file_store.yml',
											'config/outgoing_mail.yml',
											'config/security.yml'

# Default value for linked_dirs is []
append :linked_dirs, 'log', 'tmp/pids', 'tmp/cache', 'tmp/sockets', 'tmp/files',
										 'public/system', 'vendor/bundle'

# Default value for default_env is {}
# set :default_env, { path: '/opt/ruby/bin:$PATH' }

# Default value for local_user is ENV['USER']
# set :local_user, -> { `git config user.name`.chomp }

# Default value for keep_releases is 5
set :keep_releases, 7

# Uncomment the following to require manually verifying the host key before first deploy.
# set :ssh_options, verify_host_key: :secure

# Bundles settings
# set it to nil for skipping the --path flag.
set :bundle_path, -> { shared_path.join('vendor/bundle') } 
set :bundle_flags, ''

# Yarn settings
set :yarn_target_path, -> { release_path }
set :yarn_flags, ''

# Passenger settings
set :passenger_restart_with_touch, true

namespace :deploy do
  desc 'Generate Assets'
  after :publishing, :generate_assets do
  	on roles(:app) do
  		execute :mkdir, release_path.join('public/assets')
  		execute :mkdir, release_path.join('app/stylesheets/brandable_css_brands')
  		execute :touch, release_path.join('app/stylesheets/_brandable_variables_defaults_autogenerated.scss')
  	end
  end  
end

# namespace :rake do 
#   desc 'Compile Assets'
#   task :compile_canvas_assets do
#     on roles(:app) do
#       run `cd #{deploy_to}/current && bundle exec rake canvas:compile_assets RAILS_ENV=production`
#     end
#   end 
# end

namespace :bundler do
  desc 'Create Gemfile.lock'
  before :install, :create_gemfile_lock do
    on roles(:app) do
      execute :touch, release_path.join('Gemfile.lock')
    end
  end
end


